// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace EY.Domain.Entities
{
    public class Country
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string TwoLetterCode { get; set; }
        public string ThreeLetterCode { get; set; }
        public DateTime CreatedAt { get; set; } 

        public ICollection<IpAddress> IpAddresses { get; set; } 

        public Country()
        {
            CreatedAt = DateTime.UtcNow;
            IpAddresses = new List<IpAddress>();
        }
    }

}
