version: "3.4"
services:      
  redis:
    image: redis:latest
    volumes:
      - vol-redis:/data
    ports:
      - 6379:6379
      
  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - 5540:5540
    depends_on:
      - redis
    volumes:
      - vol-redis-insight:/data
    environment:

  seq:
    image: datalust/seq:latest
    volumes: 
      - vol-seq:/data
    ports:
      - 5341:5341
      - 81:81 
    environment:
      - ACCEPT_EULA=Y

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
    ports:
      - 1433:1433
    volumes:
      - vol-sqlserver:/var/opt/mssql

  web.api:
    build:
      context: . 
      dockerfile: ./EY.API/Dockerfile
    container_name: web.api
    ports:
      - 5000:5000
      - 5001:5001
    depends_on:
      - sqlserver
      - redis
      - redisinsight
      - seq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

volumes:
  vol-redis:
  vol-redis-insight:
  vol-seq:
  vol-sqlserver:
